// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal enum enum_stmt_attr_type
    {
        STMT_ATTR_UPDATE_MAX_LENGTH,
        STMT_ATTR_CURSOR_TYPE,
        STMT_ATTR_PREFETCH_ROWS,
        STMT_ATTR_PREBIND_PARAMS = 200,
        STMT_ATTR_ARRAY_SIZE,
        STMT_ATTR_ROW_SIZE,
        STMT_ATTR_STATE,
        STMT_ATTR_CB_USER_DATA,
        STMT_ATTR_CB_PARAM,
        STMT_ATTR_CB_RESULT,
        STMT_ATTR_SQL_STATEMENT,
    }
}
