// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal enum enum_session_state_type
    {
        SESSION_TRACK_SYSTEM_VARIABLES = 0,
        SESSION_TRACK_SCHEMA,
        SESSION_TRACK_STATE_CHANGE,
        SESSION_TRACK_GTIDS,
        SESSION_TRACK_TRANSACTION_CHARACTERISTICS,
        SESSION_TRACK_TRANSACTION_STATE,
    }
}
