// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal enum enum_server_command
    {
        COM_SLEEP = 0,
        COM_QUIT,
        COM_INIT_DB,
        COM_QUERY,
        COM_FIELD_LIST,
        COM_CREATE_DB,
        COM_DROP_DB,
        COM_REFRESH,
        COM_SHUTDOWN,
        COM_STATISTICS,
        COM_PROCESS_INFO,
        COM_CONNECT,
        COM_PROCESS_KILL,
        COM_DEBUG,
        COM_PING,
        COM_TIME = 15,
        COM_DELAYED_INSERT,
        COM_CHANGE_USER,
        COM_BINLOG_DUMP,
        COM_TABLE_DUMP,
        COM_CONNECT_OUT = 20,
        COM_REGISTER_SLAVE,
        COM_STMT_PREPARE = 22,
        COM_STMT_EXECUTE = 23,
        COM_STMT_SEND_LONG_DATA = 24,
        COM_STMT_CLOSE = 25,
        COM_STMT_RESET = 26,
        COM_SET_OPTION = 27,
        COM_STMT_FETCH = 28,
        COM_DAEMON = 29,
        COM_UNSUPPORTED = 30,
        COM_RESET_CONNECTION = 31,
        COM_STMT_BULK_EXECUTE = 250,
        COM_RESERVED_1 = 254,
        COM_END,
    }
}
