// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

using System.Runtime.InteropServices;

namespace CiccioSoft.MariaDb.Native
{
    internal static unsafe partial class MaListNative
    {
        [DllImport("libmariadb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("LIST *")]
        public static extern st_list* list_add([NativeTypeName("LIST *")] st_list* root, [NativeTypeName("LIST *")] st_list* element);

        [DllImport("libmariadb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("LIST *")]
        public static extern st_list* list_delete([NativeTypeName("LIST *")] st_list* root, [NativeTypeName("LIST *")] st_list* element);

        [DllImport("libmariadb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("LIST *")]
        public static extern st_list* list_cons(void* data, [NativeTypeName("LIST *")] st_list* root);

        [DllImport("libmariadb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("LIST *")]
        public static extern st_list* list_reverse([NativeTypeName("LIST *")] st_list* root);

        [DllImport("libmariadb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void list_free([NativeTypeName("LIST *")] st_list* root, [NativeTypeName("unsigned int")] uint free_data);

        [DllImport("libmariadb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("unsigned int")]
        public static extern uint list_length([NativeTypeName("LIST *")] st_list* list);

        [DllImport("libmariadb", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int list_walk([NativeTypeName("LIST *")] st_list* list, [NativeTypeName("list_walk_action")] delegate* unmanaged[Cdecl]<void*, void*, int> action, [NativeTypeName("char *")] byte* argument);
    }
}
