// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal enum mariadb_value
    {
        MARIADB_CHARSET_ID,
        MARIADB_CHARSET_NAME,
        MARIADB_CLIENT_ERRORS,
        MARIADB_CLIENT_VERSION,
        MARIADB_CLIENT_VERSION_ID,
        MARIADB_CONNECTION_ASYNC_TIMEOUT,
        MARIADB_CONNECTION_ASYNC_TIMEOUT_MS,
        MARIADB_CONNECTION_MARIADB_CHARSET_INFO,
        MARIADB_CONNECTION_ERROR,
        MARIADB_CONNECTION_ERROR_ID,
        MARIADB_CONNECTION_HOST,
        MARIADB_CONNECTION_INFO,
        MARIADB_CONNECTION_PORT,
        MARIADB_CONNECTION_PROTOCOL_VERSION_ID,
        MARIADB_CONNECTION_PVIO_TYPE,
        MARIADB_CONNECTION_SCHEMA,
        MARIADB_CONNECTION_SERVER_TYPE,
        MARIADB_CONNECTION_SERVER_VERSION,
        MARIADB_CONNECTION_SERVER_VERSION_ID,
        MARIADB_CONNECTION_SOCKET,
        MARIADB_CONNECTION_SQLSTATE,
        MARIADB_CONNECTION_SSL_CIPHER,
        MARIADB_TLS_LIBRARY,
        MARIADB_CONNECTION_TLS_VERSION,
        MARIADB_CONNECTION_TLS_VERSION_ID,
        MARIADB_CONNECTION_TYPE,
        MARIADB_CONNECTION_UNIX_SOCKET,
        MARIADB_CONNECTION_USER,
        MARIADB_MAX_ALLOWED_PACKET,
        MARIADB_NET_BUFFER_LENGTH,
        MARIADB_CONNECTION_SERVER_STATUS,
        MARIADB_CONNECTION_SERVER_CAPABILITIES,
        MARIADB_CONNECTION_EXTENDED_SERVER_CAPABILITIES,
        MARIADB_CONNECTION_CLIENT_CAPABILITIES,
        MARIADB_CONNECTION_BYTES_READ,
        MARIADB_CONNECTION_BYTES_SENT,
        MARIADB_TLS_PEER_CERT_INFO,
        MARIADB_TLS_VERIFY_STATUS,
    }
}
