// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal enum mysql_status
    {
        MYSQL_STATUS_READY,
        MYSQL_STATUS_GET_RESULT,
        MYSQL_STATUS_USE_RESULT,
        MYSQL_STATUS_QUERY_SENT,
        MYSQL_STATUS_SENDING_LOAD_DATA,
        MYSQL_STATUS_FETCHING_DATA,
        MYSQL_STATUS_NEXT_RESULT_PENDING,
        MYSQL_STATUS_QUIT_SENT,
        MYSQL_STATUS_STMT_RESULT,
    }
}
