// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal enum mysql_stmt_state
    {
        MYSQL_STMT_INITTED = 0,
        MYSQL_STMT_PREPARED,
        MYSQL_STMT_EXECUTED,
        MYSQL_STMT_WAITING_USE_OR_STORE,
        MYSQL_STMT_USE_OR_STORE_CALLED,
        MYSQL_STMT_USER_FETCHING,
        MYSQL_STMT_FETCH_DONE,
    }
}
