// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

using System.Runtime.CompilerServices;

namespace CiccioSoft.MariaDb.Native
{
    internal unsafe partial struct st_mysql_client_plugin
    {
        public int type;

        [NativeTypeName("unsigned int")]
        public uint interface_version;

        [NativeTypeName("const char *")]
        public byte* name;

        [NativeTypeName("const char *")]
        public byte* author;

        [NativeTypeName("const char *")]
        public byte* desc;

        [NativeTypeName("unsigned int[3]")]
        public _version_e__FixedBuffer version;

        [NativeTypeName("const char *")]
        public byte* license;

        public void* mysql_api;

        [NativeTypeName("int (*)(char *, size_t, int, va_list)")]
        public delegate* unmanaged[Cdecl]<byte*, nuint, int, byte*, int> init;

        [NativeTypeName("int (*)(void)")]
        public delegate* unmanaged[Cdecl]<int> deinit;

        [NativeTypeName("int (*)(const char *, const void *)")]
        public delegate* unmanaged[Cdecl]<byte*, void*, int> options;

        [InlineArray(3)]
        public partial struct _version_e__FixedBuffer
        {
            public uint e0;
        }
    }
}
