// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

using System.Runtime.CompilerServices;

namespace CiccioSoft.MariaDb.Native
{
    internal partial struct st_mysql_error_info
    {
        [NativeTypeName("unsigned int")]
        public uint error_no;

        [NativeTypeName("char[513]")]
        public _error_e__FixedBuffer error;

        [NativeTypeName("char[6]")]
        public _sqlstate_e__FixedBuffer sqlstate;

        [InlineArray(513)]
        public partial struct _error_e__FixedBuffer
        {
            public byte e0;
        }

        [InlineArray(6)]
        public partial struct _sqlstate_e__FixedBuffer
        {
            public byte e0;
        }
    }
}
