// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal unsafe partial struct st_ma_mem_root
    {
        [NativeTypeName("MA_USED_MEM *")]
        public st_ma_used_mem* free;

        [NativeTypeName("MA_USED_MEM *")]
        public st_ma_used_mem* used;

        [NativeTypeName("MA_USED_MEM *")]
        public st_ma_used_mem* pre_alloc;

        [NativeTypeName("size_t")]
        public nuint min_malloc;

        [NativeTypeName("size_t")]
        public nuint block_size;

        [NativeTypeName("unsigned int")]
        public uint block_num;

        [NativeTypeName("unsigned int")]
        public uint first_block_usage;

        [NativeTypeName("void (*)(void)")]
        public delegate* unmanaged[Cdecl]<void> error_handler;
    }
}
