// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

using System.Runtime.InteropServices;

namespace CiccioSoft.MariaDb.Native
{
    internal unsafe partial struct st_mysql_bind
    {
        [NativeTypeName("unsigned long *")]
        public uint* length;

        [NativeTypeName("my_bool *")]
        public byte* is_null;

        public void* buffer;

        [NativeTypeName("my_bool *")]
        public byte* error;

        [NativeTypeName("__AnonymousRecord_mariadb_stmt_L118_C3")]
        public _u_e__Union u;

        [NativeTypeName("void (*)(NET *, struct st_mysql_bind *)")]
        public delegate* unmanaged[Cdecl]<st_net*, st_mysql_bind*, void> store_param_func;

        [NativeTypeName("void (*)(struct st_mysql_bind *, MYSQL_FIELD *, unsigned char **)")]
        public delegate* unmanaged[Cdecl]<st_mysql_bind*, st_mysql_field*, byte**, void> fetch_result;

        [NativeTypeName("void (*)(struct st_mysql_bind *, MYSQL_FIELD *, unsigned char **)")]
        public delegate* unmanaged[Cdecl]<st_mysql_bind*, st_mysql_field*, byte**, void> skip_result;

        [NativeTypeName("unsigned long")]
        public uint buffer_length;

        [NativeTypeName("unsigned long")]
        public uint offset;

        [NativeTypeName("unsigned long")]
        public uint length_value;

        [NativeTypeName("unsigned int")]
        public uint flags;

        [NativeTypeName("unsigned int")]
        public uint pack_length;

        [NativeTypeName("enum enum_field_types")]
        public MySqlFieldTypes buffer_type;

        [NativeTypeName("my_bool")]
        public sbyte error_value;

        [NativeTypeName("my_bool")]
        public sbyte is_unsigned;

        [NativeTypeName("my_bool")]
        public sbyte long_data_used;

        [NativeTypeName("my_bool")]
        public sbyte is_null_value;

        public void* extension;

        [StructLayout(LayoutKind.Explicit)]
        internal unsafe partial struct _u_e__Union
        {
            [FieldOffset(0)]
            [NativeTypeName("unsigned char *")]
            public byte* row_ptr;

            [FieldOffset(0)]
            [NativeTypeName("char *")]
            public byte* indicator;
        }
    }
}
