// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal unsafe partial struct st_mysql_field
    {
        [NativeTypeName("char *")]
        public byte* name;

        [NativeTypeName("char *")]
        public byte* org_name;

        [NativeTypeName("char *")]
        public byte* table;

        [NativeTypeName("char *")]
        public byte* org_table;

        [NativeTypeName("char *")]
        public byte* db;

        [NativeTypeName("char *")]
        public byte* catalog;

        [NativeTypeName("char *")]
        public byte* def;

        [NativeTypeName("unsigned long")]
        public uint length;

        [NativeTypeName("unsigned long")]
        public uint max_length;

        [NativeTypeName("unsigned int")]
        public uint name_length;

        [NativeTypeName("unsigned int")]
        public uint org_name_length;

        [NativeTypeName("unsigned int")]
        public uint table_length;

        [NativeTypeName("unsigned int")]
        public uint org_table_length;

        [NativeTypeName("unsigned int")]
        public uint db_length;

        [NativeTypeName("unsigned int")]
        public uint catalog_length;

        [NativeTypeName("unsigned int")]
        public uint def_length;

        [NativeTypeName("unsigned int")]
        public uint flags;

        [NativeTypeName("unsigned int")]
        public uint decimals;

        [NativeTypeName("unsigned int")]
        public uint charsetnr;

        [NativeTypeName("enum enum_field_types")]
        public MySqlFieldTypes type;

        public void* extension;
    }
}
