// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// CiccioSoft.Mariadb: A lightweight C# class library for high-performance MariaDB database access.
// Copyright (C) 2026  Francesco Crimi.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see https://www.gnu.org/licenses/.

namespace CiccioSoft.MariaDb.Native
{
    internal unsafe partial struct st_udf_init
    {
        [NativeTypeName("my_bool")]
        public sbyte maybe_null;

        [NativeTypeName("unsigned int")]
        public uint decimals;

        [NativeTypeName("unsigned int")]
        public uint max_length;

        [NativeTypeName("char *")]
        public byte* ptr;

        [NativeTypeName("my_bool")]
        public sbyte const_item;
    }
}
